#!/usr/bin/env bash
# .crm/config.sh — CRM configuration for novique.ai
#
# Generated by init-client.sh (stack: nextjs)
# Customize as needed. All values have sensible defaults.

# Identity
CRM_PROJECT_NAME="novique.ai"
CRM_PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Repos to check for clean state (label:path pairs)
CRM_REPOS=("project:${CRM_PROJECT_ROOT}")

# Dependencies required on PATH
CRM_REQUIRED_DEPS="node npm jq"

# Build commands (empty = skip gate)
CRM_LINT_CMD="npx next lint"
CRM_TEST_CMD=""
CRM_BUILD_CMD=""  # TODO: enable once RESEND_API_KEY available locally
CRM_TYPECHECK_CMD="npx tsc --noEmit"

# Container images (name:dockerfile:context entries, empty = no images)
CRM_IMAGES=()

# VM config (0 = no VMs; entries: label:ssh_target:vmx_path:vmx_host)
CRM_VM_COUNT=0
CRM_VMS=()

# Optional integrations
CRM_BEADS_ENABLED=false
CRM_REQUIRE_TAILSCALE=false
CRM_REQUIRE_PLAN=1

# Smoke test command (empty = skip)
CRM_SMOKE_CMD=""

# Compose file to validate (empty = skip)
CRM_COMPOSE_FILE=""
